
services:

  api:
    build:
      context: .
      dockerfile: Novibet.Api/Dockerfile
    ports:
      - "5001:5001"
  
    depends_on:
      - postgres
      - worker

  worker:
    build:
      context: .
      dockerfile: Novibet.Worker/Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: novibet
      POSTGRES_USER: novibet_user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novibet_user -d novibet"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: